spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prog5_probazh
    username: prog5_probazh
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

    hu:
      pte:
        mik: debug
    root: info

server:
  port: 8888